baseurl: '/'
permalink: pretty
title: 'Валера Аквамэн'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home:
  limit_services: 6

collections:
  categories:
    output: true
    sort_by: weight
  products:
    output: true
    sort_by: price
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

#gems:
#  - jekyll-paginate-v2

# Pagination Settings
#pagination:
#  enabled: true
#  collection: 'data.news'
#  per_page: 5
#  permalink: '/news/:num/'
#  title: ' - Новости :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
